using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc.ModelBinding;            // for BindNever
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation; // for ValidateNever

namespace Airline.Data.Models
{
    public class Flight
    {
        // ← generated by DB, never bound from JSON
        public int FlightId { get; private set; }

        // ← the only six fields you send in POST/PUT
        public string FlightNumber { get; set; } = null!;
        public DateTimeOffset DepartureTime { get; set; }
        public DateTimeOffset ArrivalTime { get; set; }
        public int OriginAirportId { get; set; }
        public int DestinationAirportId { get; set; }
        public int AirplaneId { get; set; }

        // ← generated by DB on INSERT/UPDATE
        public DateTime CreatedAt { get; internal set; }
        public DateTime? UpdatedAt { get; internal set; }

        // ── navigation properties: hidden from binding & JSON ──

        [JsonIgnore]
        [BindNever]
        [ValidateNever]
        public Airport OriginAirport { get; internal set; } = null!;

        [JsonIgnore]
        [BindNever]
        [ValidateNever]
        public Airport DestinationAirport { get; internal set; } = null!;

        [JsonIgnore]
        [BindNever]
        [ValidateNever]
        public Airplane Airplane { get; internal set; } = null!;

        [JsonIgnore]
        [BindNever]
        [ValidateNever]
        public ICollection<Booking> Bookings { get; internal set; } = new List<Booking>();
    }
}
